# Generated by Django 6.0.4 on 2026-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('no_of_guests', models.IntegerField()),
                ('bookingDate', models.DateTimeField()),
            ],
        ),
    ]
